"""
MCP SERVER 3: PUBLISHER AGENT (Groq Edition)
=============================================
Role: Takes final blog package -> saves HTML, WordPress XML, pipeline report
No Groq calls — pure file I/O automation
Compatible with MCP 1.26.0+
"""

import json
import sys
import os
import re
import urllib.request
from datetime import datetime
from mcp.server.fastmcp import FastMCP

if sys.platform == "win32":
    import io
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

mcp = FastMCP("blog-publisher")

OUTPUT_DIR    = os.environ.get("BLOG_OUTPUT_DIR",
                os.path.join(os.path.expanduser("~"), "blog-pipeline-output"))
DEVTO_API_KEY = os.environ.get("DEVTO_API_KEY", "")

os.makedirs(OUTPUT_DIR, exist_ok=True)


def html_to_markdown(html: str) -> str:
    md = re.sub(r'<article[^>]*>|</article>', '', html)
    md = re.sub(r'<h1[^>]*>(.*?)</h1>', r'# \1', md, flags=re.DOTALL)
    md = re.sub(r'<h2[^>]*>(.*?)</h2>', r'## \1', md, flags=re.DOTALL)
    md = re.sub(r'<h3[^>]*>(.*?)</h3>', r'### \1', md, flags=re.DOTALL)
    md = re.sub(r'<pre[^>]*><code[^>]*>(.*?)</code></pre>', r'```\n\1\n```', md, flags=re.DOTALL)
    md = re.sub(r'<code[^>]*>(.*?)</code>', r'`\1`', md)
    md = re.sub(r'<p[^>]*>(.*?)</p>', r'\1\n\n', md, flags=re.DOTALL)
    md = re.sub(r'<strong>(.*?)</strong>', r'**\1**', md)
    md = re.sub(r'<em>(.*?)</em>', r'*\1*', md)
    md = re.sub(r'<li[^>]*>(.*?)</li>', r'- \1', md, flags=re.DOTALL)
    md = re.sub(r'<ul[^>]*>|</ul>|<ol[^>]*>|</ol>', '', md)
    md = re.sub(r'<a href="([^"]+)"[^>]*>(.*?)</a>', r'[\2](\1)', md)
    md = re.sub(r'<div class="callout"[^>]*>(.*?)</div>', r'> \1', md, flags=re.DOTALL)
    md = re.sub(r'<[^>]+>', '', md)
    return re.sub(r'\n{3,}', '\n\n', md).strip()


@mcp.tool()
def save_local_html(package_json: str) -> str:
    """Save the blog post as a styled HTML file in the output directory."""
    pkg   = json.loads(package_json)
    seo   = pkg.get("seo", {})
    slug  = seo.get("slug", "blog-post")
    title = seo.get("seo_title", pkg.get("topic", "Blog Post"))
    tags  = seo.get("tags", [])

    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <meta name="description" content="{seo.get('meta_description', '')}">
  <meta name="keywords" content="{', '.join(seo.get('secondary_keywords', []))}">
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            max-width: 860px; margin: 0 auto; padding: 2rem; color: #1a1a2e; }}
    h1 {{ color: #16213e; font-size: 2.2rem; border-bottom: 3px solid #0f3460; padding-bottom: .5rem; }}
    h2 {{ color: #0f3460; margin-top: 2rem; }}
    code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 4px; font-size: .9em; }}
    pre  {{ background: #1e1e2e; color: #cdd6f4; padding: 1.2rem; border-radius: 8px;
            overflow-x: auto; font-size: .9rem; }}
    pre code {{ background: transparent; color: inherit; padding: 0; }}
    .callout {{ background: #e8f4fd; border-left: 4px solid #0f3460;
                padding: 1rem 1.5rem; margin: 1.5rem 0; border-radius: 0 8px 8px 0; }}
    .meta {{ color: #666; font-size: .9rem; margin-bottom: 2rem; }}
    .tags span {{ background: #0f3460; color: white; padding: 3px 10px;
                  border-radius: 20px; font-size: .8rem; margin-right: 5px; }}
  </style>
</head>
<body>
  <div class="meta">
    <strong>shanmaha.com</strong> &nbsp;|&nbsp; {datetime.now().strftime('%B %d, %Y')} &nbsp;|&nbsp;
    {seo.get('reading_time_minutes', 5)} min read &nbsp;|&nbsp; {seo.get('category', 'AI')}
    &nbsp;|&nbsp; <em>Generated by Groq + MCP Pipeline</em>
  </div>
  <div class="tags">{''.join([f'<span>{t}</span>' for t in tags[:5]])}</div>
  <br>
  {pkg.get('html_content', '')}
</body>
</html>"""

    filename = f"{slug}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    filepath = os.path.join(OUTPUT_DIR, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(full_html)

    return json.dumps({
        "status":  "saved",
        "file":    filepath,
        "size_kb": round(len(full_html) / 1024, 2)
    }, indent=2)


@mcp.tool()
def generate_wordpress_export(package_json: str) -> str:
    """Create a WordPress WXR XML import file for shanmaha.com."""
    pkg   = json.loads(package_json)
    seo   = pkg.get("seo", {})
    title = seo.get("seo_title", pkg.get("topic", "Blog Post"))
    slug  = seo.get("slug", "blog-post")
    tags  = seo.get("tags", [])
    date  = datetime.now().strftime("%a, %d %b %Y %H:%M:%S +0000")

    tags_xml = "".join([
        f'<category domain="post_tag" nicename="{t.lower().replace(" ","-")}"><![CDATA[{t}]]></category>'
        for t in tags
    ])
    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:wp="http://wordpress.org/export/1.2/">
<channel>
  <wp:wxr_version>1.2</wp:wxr_version>
  <item>
    <title>{title}</title>
    <link>https://shanmaha.com/{slug}/</link>
    <pubDate>{date}</pubDate>
    <content:encoded><![CDATA[{pkg.get('html_content', '')}]]></content:encoded>
    <wp:post_type>post</wp:post_type>
    <wp:status>draft</wp:status>
    <wp:post_name>{slug}</wp:post_name>
    {tags_xml}
  </item>
</channel>
</rss>"""

    filename = f"wp_export_{slug}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xml"
    filepath = os.path.join(OUTPUT_DIR, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(xml)

    return json.dumps({
        "status":       "wp_export_created",
        "file":         filepath,
        "instructions": "WordPress Admin -> Tools -> Import -> WordPress -> upload this file"
    }, indent=2)


@mcp.tool()
def publish_to_devto(package_json: str, publish_immediately: bool = False) -> str:
    """Publish the blog post to DEV.to as draft. Requires DEVTO_API_KEY env var."""
    if not DEVTO_API_KEY:
        return json.dumps({"error": "DEVTO_API_KEY not set in environment"})

    pkg   = json.loads(package_json)
    seo   = pkg.get("seo", {})
    title = seo.get("seo_title", pkg.get("topic", "Blog Post"))
    tags  = seo.get("tags", [])

    payload = json.dumps({
        "article": {
            "title":         title,
            "body_markdown": html_to_markdown(pkg.get("html_content", "")),
            "published":     publish_immediately,
            "tags":          tags[:4],
            "series":        "shanmaha-ai-series"
        }
    }).encode()

    req = urllib.request.Request(
        "https://dev.to/api/articles",
        data=payload,
        headers={"Content-Type": "application/json", "api-key": DEVTO_API_KEY},
        method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read().decode())
        return json.dumps({
            "platform": "dev.to",
            "status":   "published" if publish_immediately else "draft_created",
            "url":      result.get("url", ""),
            "id":       result.get("id", "")
        }, indent=2)
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
def generate_pipeline_report(
    topic: str,
    html_file: str = "",
    wordpress_file: str = "",
    devto_result: str = "",
    seo_metadata: str = ""
) -> str:
    """Create a summary report of the entire pipeline run."""
    report = {
        "pipeline":        "shanmaha.com Groq + MCP Blog Pipeline",
        "run_timestamp":   datetime.now().isoformat(),
        "topic":           topic,
        "ai_provider":     "Groq",
        "outputs": {
            "html_file":      html_file      or "N/A",
            "wordpress_file": wordpress_file or "N/A",
            "devto_url":      devto_result   or "N/A"
        },
        "seo_snapshot": seo_metadata,
        "status":        "PIPELINE COMPLETE"
    }

    report_file = os.path.join(OUTPUT_DIR,
        f"pipeline_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json")
    with open(report_file, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    return json.dumps(report, indent=2)


if __name__ == "__main__":
    mcp.run(transport="stdio")
